config/routes.rb
Commish::Application.routes.draw do
  resources :games

  resources :ballers

end

app/models/baller.rb
class Baller < ActiveRecord::Base
	has_and_belongs_to_many :games
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_and_belongs_to_many :ballers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ballers_controller.rb
class BallersController < ApplicationController
  before_action :set_baller, only: [:show, :edit, :update, :destroy]

  # GET /ballers
  # GET /ballers.json
  def index
    @ballers = Baller.all
  end

  # GET /ballers/1
  # GET /ballers/1.json
  def show
  end

  # GET /ballers/new
  def new
    @baller = Baller.new
  end

  # GET /ballers/1/edit
  def edit
  end

  # POST /ballers
  # POST /ballers.json
  def create
    @baller = Baller.new(baller_params)

    respond_to do |format|
      if @baller.save
        format.html { redirect_to @baller, notice: 'Baller was successfully created.' }
        format.json { render action: 'show', status: :created, location: @baller }
      else
        format.html { render action: 'new' }
        format.json { render json: @baller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ballers/1
  # PATCH/PUT /ballers/1.json
  def update
    respond_to do |format|
      if @baller.update(baller_params)
        format.html { redirect_to @baller, notice: 'Baller was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @baller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ballers/1
  # DELETE /ballers/1.json
  def destroy
    @baller.destroy
    respond_to do |format|
      format.html { redirect_to ballers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baller
      @baller = Baller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baller_params
      params.require(:baller).permit(:name, :email, :phone, :active)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:day, :game_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ballers_helper.rb
module BallersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/ballers/_form.html.erb
<%= form_for(@baller) do |f| %>
  <% if @baller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baller.errors.count, "error") %> prohibited this baller from being saved:</h2>

      <ul>
      <% @baller.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ballers/edit.html.erb
<h1>Editing baller</h1>

<%= render 'form' %>

<%= link_to 'Show', @baller %> |
<%= link_to 'Back', ballers_path %>

app/views/ballers/index.html.erb
<h1>Listing ballers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ballers.each do |baller| %>
      <tr>
        <td><%= baller.name %></td>
	<td><%= baller.active ? 'Y' : 'N' %></td>
	<td><%= baller.email.gsub(/[a-zA-Z0-9\-_]/,'*') %></td>
        <td><%= link_to 'Show', baller %></td>
        <td><%= link_to 'Edit', edit_baller_path(baller) %></td>
        <td><%= link_to 'Destroy', baller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baller', new_baller_path %>

app/views/ballers/new.html.erb
<h1>New baller</h1>

<%= render 'form' %>

<%= link_to 'Back', ballers_path %>

app/views/ballers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baller.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @baller.email.gsub(/[a-zA-Z0-9\-_]/,'*') %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @baller.phone.gsub(/[a-zA-Z0-9]/,'*') %>
</p>

<p>
  <strong>Active:</strong>
  <%= @baller.active %>
</p>

<%= link_to 'Edit', edit_baller_path(@baller) %> |
<%= link_to 'Back', ballers_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :game_on %><br>
    <%= f.check_box :game_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Game on</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.day %></td>
        <td><%= game.game_on ? 'Yes' : 'No'  %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @game.day %>
</p>

<p>
  <strong>Game on:</strong>
  <%= @game.game_on %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Commish</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>